# Generated by Django 4.2 on 2023-05-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activity', models.CharField(blank=True, max_length=10, verbose_name='ExplorEnz EC classification')),
                ('moduloFamily', models.CharField(choices=[('UNK', 'unkwnow'), ('S', 'surface'), ('F', 'functional'), ('DISF', 'disorder functional'), ('M', 'matrice'), ('IHD', '?'), ('HD', '??'), ('ITM', '???'), ('TM', 'trans-membrane'), ('LNK', 'link'), ('IC', '????'), ('NF', '?????'), ('PS', 'peptide signal'), ('EX', '??????'), ('DIS', 'disorder'), ('DISS', 'disorder surface')], max_length=6, verbose_name='type of molulo')),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='abbreviate name')),
                ('phylogeny', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('validated', models.BooleanField(default=False)),
                ('modulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamolo.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='used name')),
                ('data_ac', models.IntegerField(verbose_name='VAZyMolO 1 CAZy_DB_id')),
                ('header', models.CharField(max_length=30)),
                ('sequence', models.TextField(blank=True)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datamolo.organism')),
            ],
        ),
        migrations.CreateModel(
            name='Subseq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamolo.protein')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamolo.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='PDB accession')),
                ('reference', models.BooleanField(default=False)),
                ('modulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamolo.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Protein_alt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='intern accession number')),
                ('name', models.CharField(max_length=100, verbose_name='used name')),
                ('data_ac', models.IntegerField(verbose_name='VAZyMolO 1 CAZy_DB_id')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datamolo.organism')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tab', models.CharField(choices=[('Prot_Infos', 'information'), ('Prot_MOTIF', 'motifs'), ('Prot_MUT', 'mutants'), ('Prot_REG', 'other regions of interest'), ('Prot_RI', 'regions of interest'), ('CAZy_GB_GP', 'genome'), ('CAZy_PDB', 'structure'), ('CAZy_PP', 'polyprotein'), ('CAZy_SP', 'single protein')], max_length=10, verbose_name='type of annotation')),
                ('data_ac', models.IntegerField()),
                ('start_origin', models.IntegerField()),
                ('end_origin', models.IntegerField()),
                ('start_profile', models.IntegerField()),
                ('end_profile', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamolo.modulo')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamolo.subseq', verbose_name='subseq of origin')),
            ],
        ),
    ]
