# Generated by Django 4.2.3 on 2024-04-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "activity",
                    models.CharField(
                        default="",
                        max_length=10,
                        verbose_name="ExplorEnz EC classification",
                    ),
                ),
                (
                    "moduloFamily",
                    models.CharField(
                        choices=[
                            ("UNK", "unknown"),
                            ("S", "surface"),
                            ("F", "functional"),
                            ("DISF", "disorder functional"),
                            ("M", "matrice"),
                            ("IHD", "?"),
                            ("HD", "hydrophobic domain"),
                            ("ITM", "???"),
                            ("TM", "trans-membrane"),
                            ("LNK", "link"),
                            ("IC", "????"),
                            ("NF", "?????"),
                            ("PS", "peptide signal"),
                            ("EX", "??????"),
                            ("DIS", "disorder"),
                            ("DISS", "disorder surface"),
                        ],
                        max_length=6,
                        verbose_name="type of molulo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organism",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Tax_id"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="scientific name"),
                ),
                (
                    "abr",
                    models.CharField(max_length=25, verbose_name="abbreviate name"),
                ),
                (
                    "group",
                    models.CharField(max_length=50, verbose_name="classification"),
                ),
                ("phylogeny", models.CharField(max_length=200)),
                ("complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validated", models.BooleanField(default=False)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("OnTheFly", "OnTheFly"),
                            ("Aligned", "Aligned"),
                            ("HMM", "HMM"),
                        ],
                        default="OnTheFly",
                        max_length=200,
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "modulo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamolo.modulo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isPP",
                    models.BooleanField(default=False, verbose_name="is PolyProtein"),
                ),
                (
                    "derivedFromPP",
                    models.BooleanField(
                        default=False, verbose_name="derived_from_PolyProtein"
                    ),
                ),
                ("genbank", models.CharField(default="", max_length=20)),
                ("name", models.CharField(max_length=100, verbose_name="used name")),
                (
                    "definition",
                    models.CharField(
                        default="", max_length=20, verbose_name="designation"
                    ),
                ),
                (
                    "data_ac",
                    models.PositiveIntegerField(verbose_name="VAZyMolO 1 CAZy_DB_id"),
                ),
                ("header", models.CharField(max_length=50)),
                ("sequence", models.TextField(blank=True)),
                ("complete", models.BooleanField(default=False)),
                (
                    "organism",
                    models.ForeignKey(
                        db_column="abr",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datamolo.organism",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("protein", models.IntegerField(null=True)),
                ("profile", models.IntegerField(null=True)),
                ("logo_prot_path", models.FilePathField(null=True)),
                ("module", models.CharField(max_length=10, null=True)),
                ("subseq", models.IntegerField(null=True)),
                ("phylo", models.IntegerField(null=True)),
                ("proteins", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subseq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("complete", models.BooleanField(default=False)),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamolo.protein",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="datamolo.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["origin", "start"],
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="PDB accession",
                    ),
                ),
                ("comment", models.CharField(default="", max_length=200)),
                ("reference", models.BooleanField(default=False)),
                ("complete", models.BooleanField(default=False)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamolo.modulo",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamolo.protein",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolyProtein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("complete", models.BooleanField(default=False)),
                (
                    "PP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mother",
                        to="datamolo.protein",
                        verbose_name="Polyprotein",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="datamolo.protein",
                        verbose_name="Real Protein",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                (
                    "genbank",
                    models.CharField(
                        max_length=30, verbose_name="Genbank accession number"
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "organism",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamolo.organism",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CDS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("sequence", models.TextField(verbose_name="nucleotide sequence")),
                ("complete", models.BooleanField(default=False)),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamolo.genome",
                    ),
                ),
                (
                    "protein",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datamolo.protein",
                        verbose_name="protein product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tab",
                    models.CharField(
                        choices=[
                            ("Prot_Infos", "information"),
                            ("Prot_MOTIF", "motif"),
                            ("Prot_MUT", "mutant"),
                            ("Prot_REG", "feature"),
                            ("Prot_RI", "interaction"),
                            ("CAZy_GB_GP", "genome"),
                            ("CAZy_PDB", "structure"),
                            ("CAZy_PP", "polyprotein"),
                            ("CAZy_SP", "single protein"),
                        ],
                        max_length=10,
                        verbose_name="type of annotation",
                    ),
                ),
                ("data_ac", models.PositiveIntegerField()),
                ("value", models.CharField(max_length=200)),
                ("start_origin", models.PositiveIntegerField()),
                ("end_origin", models.PositiveIntegerField()),
                ("start_profile", models.PositiveIntegerField(default=0)),
                ("end_profile", models.PositiveIntegerField(default=0)),
                ("complete", models.BooleanField(default=False)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamolo.modulo",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="datamolo.protein",
                        verbose_name="protein of origin",
                    ),
                ),
            ],
        ),
    ]
