# Generated by Django 4.1.5 on 2023-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protein", models.IntegerField(blank=True)),
                ("profile", models.IntegerField(blank=True)),
                ("module", models.CharField(blank=True, max_length=10)),
                ("subseq", models.IntegerField(blank=True)),
                ("phylo", models.IntegerField(blank=True)),
                ("proteins", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TempFasta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=100)),
                ("aligned", models.BooleanField(default=False)),
                ("path", models.FileField(upload_to="temp/")),
                ("filename", models.CharField(max_length=30)),
                ("profile_id", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="DATA",
        ),
        migrations.AlterModelOptions(
            name="subseq",
            options={"ordering": ["origin", "start"]},
        ),
        migrations.AlterField(
            model_name="organism",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Tax_id"
            ),
        ),
    ]
