# Generated by Django 4.2.3 on 2024-04-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modulo",
            name="activity",
        ),
    ]
