# Generated by Django 4.2.3 on 2023-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organism",
            name="abr",
            field=models.CharField(
                default="non", max_length=25, verbose_name="abbreviate name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organism",
            name="name",
            field=models.CharField(max_length=100, verbose_name="scientific name"),
        ),
    ]
