# Generated by Django 4.2.3 on 2023-09-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0002_organism_abr_alter_organism_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protein",
            name="genbank",
        ),
    ]
