# Generated by Django 4.1.5 on 2023-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "datamolo",
            "0002_session_tempfasta_delete_data_alter_subseq_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="module",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="phylo",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="profile",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="protein",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="proteins",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="subseq",
            field=models.IntegerField(null=True),
        ),
    ]
