# Generated by Django 4.2.3 on 2024-04-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0002_remove_modulo_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "EC",
                    models.CharField(
                        default="",
                        max_length=10,
                        verbose_name="ExplorEnz EC classification",
                    ),
                ),
            ],
        ),
    ]
