# Generated by Django 4.2.3 on 2023-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0003_remove_protein_genbank"),
    ]

    operations = [
        migrations.AddField(
            model_name="protein",
            name="genbank",
            field=models.CharField(default="", max_length=20),
        ),
    ]
