# Generated by Django 4.2.3 on 2023-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0004_protein_genbank"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cds",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="genome",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulo",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organism",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="polyprotein",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="protein",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="structure",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subseq",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
