# Generated by Django 4.2.3 on 2023-09-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0005_annotation_complete_cds_complete_genome_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="organism",
            field=models.ForeignKey(
                db_column="abr",
                on_delete=django.db.models.deletion.PROTECT,
                to="datamolo.organism",
            ),
        ),
    ]
