# Generated by Django 4.2.3 on 2023-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0006_alter_protein_organism"),
    ]

    operations = [
        migrations.AddField(
            model_name="protein",
            name="definition",
            field=models.CharField(
                default="", max_length=20, verbose_name="designation"
            ),
        ),
        migrations.AlterField(
            model_name="protein",
            name="header",
            field=models.CharField(max_length=50),
        ),
    ]
