# Generated by Django 4.2.3 on 2024-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0007_protein_definition_alter_protein_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="organism",
            name="group",
            field=models.CharField(
                default="", max_length=50, verbose_name="classification"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="modulo",
            name="moduloFamily",
            field=models.CharField(
                choices=[
                    ("UNK", "unknown"),
                    ("S", "surface"),
                    ("F", "functional"),
                    ("DISF", "disorder functional"),
                    ("M", "matrice"),
                    ("IHD", "?"),
                    ("HD", "hydrophobic domain"),
                    ("ITM", "???"),
                    ("TM", "trans-membrane"),
                    ("LNK", "link"),
                    ("IC", "????"),
                    ("NF", "?????"),
                    ("PS", "peptide signal"),
                    ("EX", "??????"),
                    ("DIS", "disorder"),
                    ("DISS", "disorder surface"),
                ],
                max_length=6,
                verbose_name="type of molulo",
            ),
        ),
    ]
