# Generated by Django 4.2.3 on 2024-02-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0008_organism_group_alter_modulo_modulofamily"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="logo_prot_path",
        ),
    ]
