# Generated by Django 4.2.3 on 2024-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0009_remove_session_logo_prot_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="logo_prot_path",
            field=models.FilePathField(null=True),
        ),
    ]
