# Generated by Django 4.2.3 on 2024-03-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0010_session_logo_prot_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="method",
            field=models.CharField(
                choices=[("OnTheFly", "OnTheFly"), ("HMM", "HMM")],
                default=("OnTheFly", "OnTheFly"),
                max_length=200,
            ),
        ),
    ]
