# Generated by Django 4.2.3 on 2024-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamolo", "0011_profile_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="method",
            field=models.CharField(
                choices=[("OnTheFly", "OnTheFly"), ("HMM", "HMM")],
                default="OnTheFly",
                max_length=200,
            ),
        ),
    ]
