# Generated by Django 4.2.3 on 2024-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=200, verbose_name="keywords")),
                (
                    "option",
                    models.CharField(
                        choices=[
                            ("keywords", "keywords"),
                            ("DB_ac", "DB_ac"),
                            ("protein_id", "protein_id"),
                            ("Modulo", "Modulo"),
                        ],
                        default="DB_ac",
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
