# Generated by Django 4.2.3 on 2024-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VazySearch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchquery",
            name="query",
            field=models.CharField(max_length=200, verbose_name="keywords"),
        ),
    ]
