# Generated by Django 4.2.3 on 2024-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VazySearch", "0002_alter_searchquery_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquery",
            name="option",
            field=models.CharField(
                choices=[
                    ("keywords", "keywords"),
                    ("DB_ac", "DB_ac"),
                    ("Modulo", "Modulo"),
                ],
                default="DB_ac",
                max_length=25,
            ),
        ),
    ]
