# Generated by Django 4.2.3 on 2024-02-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VazySearch", "0003_searchquery_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchquery",
            name="option",
            field=models.CharField(
                choices=[
                    ("keywords", "keywords"),
                    ("DB_ac", "DB_ac"),
                    ("protein_id", "protein_id"),
                    ("Modulo", "Modulo"),
                ],
                default="DB_ac",
                max_length=25,
            ),
        ),
    ]
